import { PublicDraftsClient } from "./PublicDraftsClient";

export default async function PublicDraftsPage() {
  // TODO: Fetch real data from DAL queries
  // For now, using mock data similar to Figma design

  const allPublicDrafts = [
    {
      id: "1",
      name: "Elite Tournament Pool",
      participants: 89,
      maxParticipants: 150,
      prizePool: 5000,
      entryFee: 25,
      difficulty: "expert" as const,
      featured: true,
      spotsLeft: 61,
      startDate: "Mar 18, 2026",
    },
    {
      id: "2",
      name: "Beginner Bracket Bash",
      participants: 34,
      maxParticipants: 100,
      prizePool: 500,
      entryFee: 0,
      difficulty: "beginner" as const,
      featured: false,
      spotsLeft: 66,
      startDate: "Mar 19, 2026",
    },
    {
      id: "3",
      name: "High Rollers Championship",
      participants: 45,
      maxParticipants: 50,
      prizePool: 10000,
      entryFee: 100,
      difficulty: "expert" as const,
      featured: true,
      spotsLeft: 5,
      startDate: "Mar 17, 2026",
    },
    {
      id: "4",
      name: "Daily Free Roll",
      participants: 156,
      maxParticipants: 500,
      prizePool: 1000,
      entryFee: 0,
      difficulty: "beginner" as const,
      featured: false,
      spotsLeft: 344,
      startDate: "Mar 16, 2026",
    },
    {
      id: "5",
      name: "Intermediate Madness",
      participants: 67,
      maxParticipants: 200,
      prizePool: 3000,
      entryFee: 15,
      difficulty: "intermediate" as const,
      featured: false,
      spotsLeft: 133,
      startDate: "Mar 18, 2026",
    },
    {
      id: "6",
      name: "Weekend Warriors Special",
      participants: 112,
      maxParticipants: 150,
      prizePool: 2500,
      entryFee: 20,
      difficulty: "intermediate" as const,
      featured: false,
      spotsLeft: 38,
      startDate: "Mar 20, 2026",
    },
    {
      id: "7",
      name: "Pro League Playoff",
      participants: 78,
      maxParticipants: 100,
      prizePool: 7500,
      entryFee: 50,
      difficulty: "expert" as const,
      featured: true,
      spotsLeft: 22,
      startDate: "Mar 17, 2026",
    },
    {
      id: "8",
      name: "Community Cup",
      participants: 203,
      maxParticipants: 1000,
      prizePool: 500,
      entryFee: 0,
      difficulty: "beginner" as const,
      featured: false,
      spotsLeft: 797,
      startDate: "Mar 19, 2026",
    },
    {
      id: "9",
      name: "Mid-Stakes Showdown",
      participants: 45,
      maxParticipants: 75,
      prizePool: 1800,
      entryFee: 10,
      difficulty: "intermediate" as const,
      featured: false,
      spotsLeft: 30,
      startDate: "Mar 21, 2026",
    },
    {
      id: "10",
      name: "Championship Series Finals",
      participants: 92,
      maxParticipants: 100,
      prizePool: 15000,
      entryFee: 75,
      difficulty: "expert" as const,
      featured: true,
      spotsLeft: 8,
      startDate: "Mar 16, 2026",
    },
  ];

  return <PublicDraftsClient drafts={allPublicDrafts} />;
}
