services:
  db:
    image: postgres:16-alpine
    container_name: fantasy_madness_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasy_madness
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fantasy_madness"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - fm_pgdata:/var/lib/postgresql/data

  fake-sportradar:
    build:
      context: ./apps/fake-sportradar
    ports:
      - "4010:4010"
    environment:
      PORT: "4010"
      TICK_SECONDS: "10"
      AUTO_ADVANCE: "true"
      SPORTRADAR_API_KEY: "devkey"
    depends_on:
      db:
        condition: service_healthy

  ingest:
    build:
      context: .
      dockerfile: apps/ingest/Dockerfile
    environment:
      SPORTRADAR_BASE_URL: "http://fake-sportradar:4010"
      SPORTRADAR_API_KEY: "devkey"

      # Prisma needs this:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/fantasy_madness?schema=public"
      DIRECT_URL:  "postgresql://postgres:postgres@db:5432/fantasy_madness?schema=public"
    depends_on:
      db:
        condition: service_healthy
      fake-sportradar:
        condition: service_started

volumes:
  fm_pgdata:
