services:
  web:
    env_file:
      - ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  ingest:
    env_file:
      - ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/ingest.Dockerfile
    environment:
      NODE_ENV: production
