services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - fm-network
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    container_name: fm-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - fm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    env_file:
      - ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/web.Dockerfile
      args:
        DISABLE_TIMER_WORKER: "false"
    container_name: fm-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - fm-network

  ingest:
    env_file:
      - ../../.env
    build:
      context: ../../
      dockerfile: infra/docker/ingest.Dockerfile
    container_name: fm-ingest
    restart: unless-stopped
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    networks:
      - fm-network

networks:
  fm-network:
    driver: bridge

volumes:
  redis-data:
  caddy-data:
  caddy-config:
